integrations:
  prometheus_remote_write:
    - basic_auth:
        password: admin
        username: admin
      url: http://prometheus:9090
  agent:
    enabled: true
    relabel_configs:
      - action: replace
        source_labels:
          - agent_hostname
        target_label: instance
      - action: replace
        target_label: job
        replacement: "integrations/agent-check"
    metric_relabel_configs:
      - action: keep
        regex: (prometheus_target_sync_length_seconds_sum|prometheus_target_scrapes_.*|prometheus_target_interval.*|prometheus_sd_discovered_targets|agent_build.*|agent_wal_samples_appended_total|process_start_time_seconds)
        source_labels:
          - __name__
  # Add here any snippet that belongs to the `integrations` section.
  # For a correct indentation, paste snippets copied from Grafana Cloud at the beginning of the line.
  postgres_exporter:
    enabled: true
    instance: '<postgres-instance-demoDB>' # must match instance used in logs
    data_source_names:
      - 'postgresql://postgres:postgres@postgres:5432/demoDB' # replace with your connection string
#logs:
#  configs:
#    - clients:
#        - basic_auth:
#            password: <your_loki_pass>
#            username: <your_loki_user>
#          url: <your_loki_url>
#      name: integrations
#      positions:
#        filename: /tmp/positions.yaml
#      scrape_configs:
#        # Add here any snippet that belongs to the `logs.configs.scrape_configs` section.
#        # For a correct indentation, paste snippets copied from Grafana Cloud at the beginning of the line.
#        - job_name: integrations/postgres_exporter
#          static_configs:
#            - targets:
#                - localhost
#              labels:
#                instance: '<your-instance-name>'
#                __path__: /usr/local/var/log/postgres.log
#                job: integrations/postgres_exporter
metrics:
  configs:
    - name: integrations
      remote_write:
        - basic_auth:
            password: admin
            username: admin
          url: http://prometheus:9090
      scrape_configs:
      # Add here any snippet that belongs to the `metrics.configs.scrape_configs` section.
      # For a correct indentation, paste snippets copied from Grafana Cloud at the beginning of the line.
  global:
    scrape_interval: 60s
  wal_directory: /tmp/grafana-agent-wal
