version: "3"
services:
  postgres_dev:
    image: postgres
    container_name: java-postgres-dev
    environment:
      - POSTGRES_USER=usr
      - POSTGRES_PASSWORD=pwd
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=demoDB
    ports:
    - "5430:5432"
  postgres_test:
    image: postgres
    container_name: java-postgres-test
    environment:
      - POSTGRES_USER=usr
      - POSTGRES_PASSWORD=pwd
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=testDB
    ports:
      - "5440:5432"
