version: "3"
services:
  postgres:
    image: postgres
    container_name: java-postgres
    environment:
      - POSTGRES_USER=usr
      - POSTGRES_PASSWORD=pwd
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=demoDB
    ports:
    - 5432:5432

