spring:
  datasource:
    url: jdbc:h2:mem:maindbt
#    username: dbuser
#    password: dbpass
#    driver-class-name: com.mysql.jdbc.Driver
#    initialization-mode: always
#    schema: data/schema.sql
#    data: data/data.sql
  sql:
    init:
      mode: always
#      data-locations: data/data.sql
#      schema-locations: data/schema.sql
#  h2:
#    console:
#      console.enabled: true
#      path: /h2-console
#      settings:
#        web-allow-others: true


  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true
    show-sql: false

logging:
  level:
    ROOT: ERROR

server:
  port: 8080
  error:
     include-exception: true
     include-stacktrace: always
