spring:
  main:
    allow-bean-definition-overriding: true
  shell:
    interactive:
      enabled: true
  data:
    mongodb:
#      authentication-database: none
#      username: none
#      password: none
      port: 27017
      host: localhost
      database: otus
#      port: 0 # when flapdoodle using

#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# ---------------------------------
de:
  flapdoodle:
    mongodb:
      embedded:
        version: 6.0.5
    embed:
      mongo:
        distribution:
          IFeatureAwareVersion: 6.0.5

# Properties only for the `ide` profile.
  config:
    activate:
      on-profile: ide
de.flapdoodle.mongodb.embedded.version: 6.0.5

# ---------------------------------
mongock:
#  runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.hw.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

# ---------------------------------
systemProp:
  de:
    flapdoodle:
      os:
        explain: true
# ---------------------------------
logging:
  level:
    root: info
    de.flapdoodle.os.common.attributes: warn
    de.flapdoodle.embed.mongo.spring.autoconfigure.EmbeddedMongoAutoConfiguration: warn
    de.flapdoodle.embed.mongo.distribution.IFeatureAwareVersion: warn

