version: "3"
services:
  postgres_dev:
    image: postgres:15
    container_name: java-postgres-dev
    environment:
      - POSTGRES_USER=usr
      - POSTGRES_PASSWORD=pwd
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=demoDB
    ports:
      - "5430:5432"
    command: [ "postgres", "-c", "log_statement=all" ]
