version: '3'
services:
  app-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: java-spring-rest-dev-37
    container_name: service-app-cont
    restart: always
    depends_on:
      - postgres
      - prometheus
    ports:
      - "8080:8080"
      - "8090:8090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # Эти свойства перегружают соответствующие в application.yml
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/demoDB
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://postgres:5432/demoDB
      - SPRING_LIQUIBASE_USER=postgres
      - SPRING_LIQUIBASE_PASSWORD=postgres
    volumes:
      - app-storage:/tmp/app
      - ./modules:/var/www/html/modules

  postgres:
    image: "postgres:15"
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - POSTGRES_URL=jdbc:postgresql://localhost:5430
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=demoDB
    command: [ "postgres", "-c", "log_statement=all" ]
    volumes:
      - postgres-storage:/var/lib/postgresql/data

  prometheus:
    image: "prom/prometheus:v2.48.1"
    container_name: prometheus
    restart: always
    ports:
      - "9095:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-storage:/prometheus

volumes:
  postgres-storage: {}
  prometheus-storage: {}
  app-storage: {}

