spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/demoDB
    username: usr
    password: pwd
#  flyway:
#    url: jdbc:postgresql://localhost:5430/demoDB
#    user: usr
#    password: pwd

  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: false
    show-sql: false

server:
  port: 8080
  error:
     include-exception: true
     include-stacktrace: always

logging:
  level:
    ROOT: ERROR
#    org.springframework.jdbc.core.JdbcTemplate: TRACE
