spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5430/demoDB
    username: usr
    password: pwd
  flyway:
    url: jdbc:postgresql://localhost:5430/demoDB
    user: usr
    password: pwd

logging:
  level:
    ROOT: ERROR
    org.springframework.jdbc.core.JdbcTemplate: TRACE
    io.r2dbc.postgresql.QUERY: DEBUG # for queries
    io.r2dbc.postgresql.PARAM: DEBUG # for parameters

server:
  port: 8080
  error:
     include-exception: true
#     include-stacktrace: always
