server:
  port: 8080
  error:
    include-exception: true
#     include-stacktrace: always

spring:
  application:
    name: spring-study-circuit-breaker
  datasource:
    url: jdbc:postgresql://localhost:5432/demoDB
    username: postgres
    password: postgres
  liquibase:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    enabled: true

  sql:
    init:
      mode: always
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: falserest
    show-sql: false

logging:
#  file:
#    path: ./logs/
  pattern:
    console: true
  level:
    ROOT: ERROR

spring.profiles.include:
  - 'actuator'
  - 'resilience4j'
  - 'hateoas'
