version: '3.8'
services:
  app-client:
    build:
      context: .
      dockerfile: Dockerfile
    image: spring-study-web-client
    container_name: app-cont-web-client-37
    restart: always
    ports:
      - "8981:8981"
      - "8091:8091"
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - FEIGN_CLIENT_NAME=call-to-books-store
      - FEIGN_CLIENT_URL=http://127.0.0.1:8080
    volumes:
      - app-client-storage:/tmp/app

  prometheus:
    image: "prom/prometheus:v2.48.1"
    container_name: prometheus
    restart: always
    ports:
      - "9095:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-storage:/prometheus

volumes:
  app-client-storage: {}
  prometheus-storage: {}
