version: "3"
services:
  postgres_dev:
    image: postgres:15
    container_name: java-postgres-batch
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=demoDB
    ports:
      - "5432:5432"
    volumes:
      - batch-data:/var/lib/postgresql/data
    command: [ "postgres", "-c", "log_statement=all" ]

volumes:
  batch-data:

